from . import vehicle
from . import document
from . import fuel_log
from . import transaction_type
from . import hr_extend
from . import fleet_manager_assignment
from . import battery
from . import tyre
from . import vehicle_image
from . import simply_fleet_camera
from . import vehicle_asset
from . import inspection
from . import work_order
from . import barcode_wizard
