{
    'name': 'Employee Uniform Management',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Manage employee uniforms and accessories',
    'description': "Manage employee uniforms including tracking assignments and returns",
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'depends': ['hr', 'web'],
    'data': [
        'security/uniform_security.xml',
        'security/ir.model.access.csv',
        'data/uniform_type_data.xml',
        'data/uniform_item_data.xml',
        'data/uniform_size_data.xml',
        'views/uniform_item_views.xml',
        'views/uniform_assignment_views.xml',
        'views/uniform_type_views.xml',
        'views/uniform_size_views.xml',
        'views/uniform_return_views.xml',
        'views/hr_employee_views.xml',
        'wizard/views/mass_assignment_view.xml',
        'report/uniform_assignment_report_template.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
